feat(evaudio): set audio output port to use
Previously, only the audio sink is set. Now can select from using
available ports of the sink.

diff --git a/src/evaudio b/src/evaudio
--- a/src/evaudio
+++ b/src/evaudio
@@ -7,36 +7,24 @@
 #
 #== Synopsis
 #
-# evaudio [options] --sink sink-id
-# evaudio [options] sink-id
-# evaudio [options] -- sink-id
-#
-#
-#== Options
-#
-# -s sink-id, --sink sink-id
-#    The sink ID to set as the default audio output to use. If unset, select from
-#    a list of available sinks.
+# evaudio
 
 
 
 . "$EVUTILS_HOME/lib/log"
 . "$EVUTILS_HOME/lib/audio"
 . "$EVUTILS_HOME/lib/list"
-. "$EVUTILS_HOME/lib/encode"
 
-_sinks=""
-_sink=""
+_audio_output_description=""
+_sink_id=""
+_sink_port_id=""
 
-# Set the sink to use.
-_set_sink() {
-    if [ "$_sink" ]; then
-        _sinks=$(get_sinks)
-        return
-    fi
-    _sinks=$(get_alt_sinks)
-    if ! [ "$_sinks" ]; then
-        log_status "No alternate sinks available. Exiting..."
+# Set the audio output to use.
+#
+_set_audio_output() {
+    audio_outputs=$(get_alt_outputs)
+    if ! [ "$audio_outputs" ]; then
+        log_status "No alternate audio outputs available. Exiting..."
         exit
     fi
 
@@ -46,73 +34,26 @@ _set_sink() {
         evmenu_opts="${evmenu_opts} --term"
     fi
 
-    sink_description=$(get_col --idx 2 --delim "," --list "$_sinks" | eval evmenu "$evmenu_opts" --prompt "'Set Audio Output'")
-    if ! [ "$sink_description" ]; then
+    output_selection=$(get_keys --delim " , " --list "$audio_outputs" | eval evmenu "$evmenu_opts" --prompt "'Set Audio Output'")
+    if ! [ "$output_selection" ]; then
         exit
     fi
-    _sink=$(echo "$_sinks" | awk -F "," "/,$(encode --enc AWK_REGEX -- "$sink_description")/ {print \$1}")
+    _audio_output_description=$output_selection
+    _sink_id=$(get_val --key "$output_selection" --idx 2 --delim " , " --list "$audio_outputs")
+    _sink_port_id=$(get_val --key "$output_selection" --idx 3 --delim " , " --list "$audio_outputs")
 }
 
-# Set default sink.
+# Set audio output.
+#
 _run() {
-    sink_description=$(get_val --key "$_sink" --idx 2 --delim "," --list "$_sinks")
-    { set_def_sink "$_sink" && log_status "Default sink set to ${sink_description}"; } \
-        || log_error "Setting default sink to ${sink_description} failed."
+    { set_output "$_sink_id" "$_sink_port_id" && log_status "Audio output set to ${_audio_output_description}."; } ||
+        log_error "Setting audio output to ${_audio_output_description} failed."
 }
 
 main() {
-    while [ "$1" ]; do
-        case $1 in
-            -s|--sink)
-                if get_sinks | grep -Fq -e "${2},"; then
-                    if get_alt_sinks | grep -Fq -e "${2},"; then
-                        _sink=$2
-                    else
-                        log_warning "${2} already the default sink. Ignoring..."
-                    fi
-                else
-                    log_warning "Invalid sink ID ${2}. Ignoring..."
-                fi
-                shift
-                ;;
-            --)
-                shift
-                break
-                ;;
-            -?*)
-                log_warning "Unknown option ${1}. Ignoring..."
-                ;;
-            *)
-                if get_sinks | grep -Fq -e "${1},"; then
-                    if get_alt_sinks | grep -Fq -e "${1},"; then
-                        _sink=$1
-                    else
-                        log_warning "${1} already the default sink. Ignoring..."
-                    fi
-                else
-                    log_warning "Invalid sink ID ${1}. Ignoring..."
-                fi
-                ;;
-        esac
-        shift
-    done
-
-    while [ "$1" ]; do
-        if get_sinks | grep -Fq -e "${1},"; then
-            if get_alt_sinks | grep -Fq -e "${1},"; then
-                _sink=$1
-            else
-                log_warning "${1} already the default sink. Ignoring..."
-            fi
-        else
-            log_warning "Invalid sink ID ${1}. Ignoring..."
-        fi
-        shift
-    done
-
-    _set_sink
+    _set_audio_output
     _run
 }
 
-main "$@"
+main
 
